# Generated by Django 4.0.2 on 2022-03-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlecategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='URL Title')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='Article Image')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Inactive')),
                ('selected_categories', models.ManyToManyField(to='articles.ArticleCategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
