# Generated by Django 4.0.2 on 2022-02-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(verbose_name='price')),
                ('short_description', models.CharField(db_index=True, max_length=300, null=True, verbose_name='short description')),
                ('description', models.TextField(db_index=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='active / inactive')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_delete', models.BooleanField(verbose_name='deleted / not deleted')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='title')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='url title')),
                ('is_active', models.BooleanField(verbose_name='active / inactive')),
                ('is_delete', models.BooleanField(verbose_name='deleted / not deleted')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=200, verbose_name='tag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', to='product.ProductCategory', verbose_name='category'),
        ),
    ]
