# Generated by Django 4.0.2 on 2022-02-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_delete',
        ),
    ]
