# Generated by Django 4.0.2 on 2022-02-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('fullname', models.CharField(max_length=300, verbose_name='full name')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read_by_admin', models.BooleanField(verbose_name='read by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('response', models.TextField(blank=True, null=True, verbose_name="admin's Response")),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'List of Contacts',
            },
        ),
    ]
