# Generated by Django 4.0.2 on 2022-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('site_url', models.CharField(max_length=200, verbose_name='Site URL')),
                ('site_address', models.CharField(max_length=300, verbose_name='Site Address')),
                ('site_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Phone')),
                ('site_fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Fax')),
                ('site_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Site Email')),
                ('about_us_text', models.TextField(verbose_name='About Us Text')),
                ('site_copy_right', models.TextField(verbose_name='Copyright Text')),
                ('site_logo', models.ImageField(upload_to='images/site-setting/', verbose_name='Site Logo')),
                ('is_main_setting', models.BooleanField(verbose_name='Site Main Settings')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
