# Generated by Django 4.0.2 on 2022-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Slider Description')),
                ('url_title', models.CharField(max_length=200, verbose_name='URL Title')),
                ('url', models.URLField(verbose_name='URL Address')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='Slider Image')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
